### ISSUE TITLE
[BUG] Locked out when using Biometric login on non-enabled devices

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#39] opened 2020-08-24 09:36 UTC
**Describe the bug**
Enabling biometric login on a device that does not support this feature locks the user out of the wallet

**To Reproduce**
1. Go to Settings
2. Enable biometric login
3. Close the app from multitasking
4. Open the wallet
5. Error message displayed at login

ERROR
An error ocurred

Unknown and very strange error!BIOMETRIC_NOT_ENROLLED

**Expected behavior**
There needs to be handling for devices that do no support biometric login

**Smartphone (please complete the following information):**
 - Device: S6

**Comment by t3nshi** [comment] 2020-08-24 16:05
That's a good one... I will check and try to reproduce and report back soon

**Comment by t3nshi** [comment] 2020-08-28 19:23
I tried and when there is no fingerprint it allowed me to introduce the pattern or the pin for the phone, It worked in a lenovo and in a samsung. It would require more details to be able to reproduce this, since I currently was not able to reproduce with the given instructions.

Either way, I used the error you posted to filter this kind of problem and disable the biometric enrolement when this error is detected. Please try and confirm, or otherwise provide additional information.

**Comment by danielwwf** [comment] 2020-08-29 00:48
Works fine now on note 10

**Comment by t3nshi** [comment] 2020-08-31 14:45
I already checked on several devices, so I will close it and if someone checks anything else about it please reopen it.

**Closed as completed by t3nshi** 2020-08-31 14:45 UTC
Labels: bug
