### ISSUE TITLE
Using Camera for KYC

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#8] opened 2020-08-18 13:51 UTC
**Describe the bug**
Some devices no longer support using the camera to take pictures.
Samsung Note10+: No camera since 0.4.3
Samsung Note8: Camera works, last test on 0.4.5
Samsung S9+: No camera
Huawei Pro20+: No camera

**There must be a way to debug this, the argument that this an aver issue and we can't do anything about it doesn't work because the same solution works in the BRM.** 

In addition, this was working fine on the Note10 for most releases. 

**To Reproduce**
1. Do KYC

**Expected behavior**
All devices should be able to take pictures.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Note8, S9+, 10 
 - OS: Android
 - OS Version 9 and newer
 - App Version 0.4.5

**Comment by t3nshi** [comment] 2020-08-18 13:59
I will check on my end if there is anything we can solve ourselves. Let me get back to you later

**Comment by t3nshi** [comment] 2020-08-18 22:34
After a lot of research and digging, we found out that the issue is present in a lot of apps that use this kind of functionality and is due to some different behaviour that android includes in android 9 and 10. So we already found a way to modify the plugin for the inappBrowser and made some changes that appear to work.. at least in a phone i have running on android 9. So let me know about droid 9

**Comment by danielwwf** [comment] 2020-08-18 23:30
Camera works now but after taking a picture no upload happens.
 Check video no_upload.mp4 in development channel on slack

**Comment by t3nshi** [comment] 2020-08-19 13:02
Can you detail the devices which present this behaviour and which of them are working alright detailing the OS version so we can try to fix it in a way that cover all and not just a small fraction? For example I had 3 devices, lenovo K5, and 2 moto Z2 force. In k5 and one Z2 it worked before, with droid 7 and 8, but in the z2 with droid 9 it wasn't working, it was just showing the gallery, now it works on all three devices. Thank you for your input.

**Comment by t3nshi** [comment] 2020-08-19 13:41
There is issue #15 related to this same that seems to be happening only on android 10

**Comment by t3nshi** [comment] 2020-08-19 13:46
Since this issue clearly stated that camera was not showing and now does it will be closed as resloved. The new issue about not getting the image is already handled in #15 so we will keep tracking these deatils there.

**Closed as completed by t3nshi** 2020-08-19 13:46 UTC
Labels: bug, test feedback
