### ISSUE TITLE
VITALLY IMPORTANT - MUST BE FIXED ASAP - CSC LOGO IN IPAD FOR APP LISTING

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#109] opened 2020-09-21 10:36 UTC
IOS / IPAD 12 VERSION OF CR8 WALLET HAS CSC LOGO. (cr8 wallet 0.5.0)

This is the one thing we should NEVER EVER SHOW. HUGE MISTAKE. Please get this fixed **yesterday**!

THIS WHOLE ISSUE CAN BE CLOSED IF THIS HAS ALREADY BEEN TAKEN CARE OF IN LATER VERSIONS - I ONLY HAVE THE 0.5.0 IOS VERSION AS THE LATEST UPDATE.

**Reason**
We can never ever be seen to be linked to the CasinoCoin foundation. Having the logo suggests that we're part of the same team.

**Description**
In iOS / iPad 'settings' section, when you scroll down and see the list of installed apps, the cr8 wallet comes with a CSC logo. Screenshot attached.

**Screenshots**
I
![IMG_20200921_121310](https://user-images.githubusercontent.com/69824025/93757379-f3e38900-fc06-11ea-9804-65f4307d99ce.jpg)
![IMG_20200921_121319](https://user-images.githubusercontent.com/69824025/93757412-02ca3b80-fc07-11ea-9f2d-a7e306e0bc17.jpg)

llustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment] 2020-09-21 13:01
This was already fixed, it was a bit tricky, we would need to se how to get the version pushed to the app store. I will try to figure it out.

**Comment by georgemac70cr8** [comment] 2020-09-21 13:03
great news that already been sorted. i'll close.

**Comment by t3nshi** [comment] 2020-09-21 13:18
I will leave it open for now... so we are still aware that the issue is still current... We will close it when we validated that is fixed once the app gets pushed to the App store.

**Comment by t3nshi** [comment] 2020-09-22 13:24
Can you update to version 0.5.6 and validate that is completely fixed please?

**Comment by georgemac70cr8** [comment] 2020-09-22 13:32
please send us the ios version 0.5.6

**Comment by t3nshi** [comment] 2020-09-22 13:39
I thought it was already on the App store, since I had report from other ios issues of other users that 0.5.6 fixed the issue... It was not the case?

**Comment by georgemac70cr8** [comment] 2020-09-22 13:46
the latest update wasn't accepted at the store.

**Comment by t3nshi** [comment] 2020-09-22 13:52
I realized now that we have it on testflight.. that's why I was having the reports from the other issues. We can wait a bit for the App store version or you could reach @whywefight  to access testfilght.

**Comment by georgemac70cr8** [comment] 2020-09-22 14:01
can't you just check in that case?

**Comment by t3nshi** [comment] 2020-09-22 16:44
what do you mean?

**Comment by georgemac70cr8** [comment] 2020-09-22 17:10
i just meant couldn't you test it on your ios phone / ipad and check that the logo has now been changed to cr8. In the meantime, i will ask @whywefight to check in testflight. i don't have access to testflight.

**Comment by t-jacobi** [comment] 2020-09-22 20:35
For me in iOS 13.6 iphone 6s the issue is fixed. Previous version has shown the csc logo. 
But i had to delete and reinstall the app 0.5.6 from testflight.

**Comment by t3nshi** [comment] 2020-09-23 14:14
Ok thanks for your input. this seems to validate that it was fixed on last version. I will close the issue then.

**Closed as completed by t3nshi** 2020-09-23 14:14 UTC
Labels: UI, test
