### ISSUE TITLE
[WARNING MESSAGE BOX FOR RECOVERY PHRASE]

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#17] opened 2020-08-19 11:00 UTC
**Section or interface element**
When setting up account, the warning message comes up on the device to tell you to make yoiu understand what you need to do if you lose account login details. This looks strange, like for a fraction of a second there's a flicker / or it duplicates the msg box on top of the same box - ?

**Description**
Please have a look on your android phones and see what I mean. I have attached an old screenshot (before the screenshot was disabled) but it should give you enough for you to look into it and see what I mean.

**Screenshots**
attached
![Screenshot_20200819_125437_com android gallery3d](https://user-images.githubusercontent.com/69824025/90626966-cd06f100-e21b-11ea-81d6-f652aea70505.jpg)

Matt's phone showed the same too.

**Comment by t3nshi** [comment] 2020-08-19 13:06
I will try to look into this. Your process is not very clear, but I think I finally figured out what you mean and where to look. I will let you know soon when I am able to reproduce the behaviour.

**Comment by t3nshi** [comment] 2020-08-19 20:35
After some thinkering I think I could reproduce it and figured it out. I will solve it for next version.

**Comment by t3nshi** [comment] 2020-08-31 14:53
This was fixed some versions ago, and I validated on several devices. Since nobody has given any feedback about it I will close it now. Feel free to reopen if you realize that there is still something pending here.

**Closed as completed by t3nshi** 2020-08-31 14:53 UTC
Labels: UI
