### ISSUE TITLE
[UI-FIX] Container Styling

### ISSUE THREAD

**Issue by moatazkhalifa** [asgiom/cr8-brm-mobile-issues#22] opened 2020-08-19 16:25 UTC
Instead of creating a separate issue for every container, I'm going to list all container styling issues below:

- Container width for Send/Receive/Transactions and Buy/Sell is different from Home
- Content padding is messed up under Transactions
- **Odd formatting:**
    Please use a standard formatting for all headers and text across all screens: Send/Receive/Transactions are all different. Headers (labels) are ORANGE on Send, and the font is much smaller when compared to 'Receive', for instance.
- Under Buy/Sell, header text and AccountID are all messed up, center aligned (while everything on the app is not)

FIX:

Please use a standard CSS class for all headers and text.

**Comment by t3nshi** [comment] 2020-08-19 17:34
> Odd formatting:
> Please use a standard formatting for all headers and text across all screens: Send/Receive/Transactions are all different. Headers (labels) are ORANGE on Send, and the font is much smaller when compared to 'Receive', for instance.

great I can see that. So what do you want as a solution here.

**Comment by t3nshi** [comment] 2020-08-19 17:36
> Under Buy/Sell, header text and AccountID are all messed up, center aligned (while everything on the app is not)
 
As I've been telling you, this is working as an external component. Do you want me to pass an option so it won't align to center but to left?

**Comment by moatazkhalifa** [comment] 2020-08-19 17:41
> > Odd formatting:
> > Please use a standard formatting for all headers and text across all screens: Send/Receive/Transactions are all different. Headers (labels) are ORANGE on Send, and the font is much smaller when compared to 'Receive', for instance.
> 
> great I can see that. So what do you want as a solution here.

Let's not re-invent the wheel. So if you could replicate the same styling of 'Send' screen to be the standard across all screen, it would be great.

> > Under Buy/Sell, header text and AccountID are all messed up, center aligned (while everything on the app is not)
> 
> As I've been telling you, this is working as an external component. Do you want me to pass an option so it won't align to center but to left?

Left align while keeping the same padding used everywhere, and the accountID displayed on one-line will be great. Again, only looking to have everything look the same, as currently, each screen has it's own formatting/styling

**Comment by t3nshi** [comment] 2020-08-19 17:49
> Content padding is messed up under Transactions

I don't understand this, I compared and checked a lot and still don't get it. Can you elaborate or show a screenshot?

**Comment by moatazkhalifa** [comment] 2020-08-19 18:06
When there are no transactions, it displays 'No transactions to show' and it has no padding to the left. When there are transactions, the container looks ok.

**Comment by t3nshi** [comment] 2020-08-19 19:48
Thanks, that was way more clear. I will fix it right away.

**Comment by t3nshi** [comment] 2020-08-28 19:18
> Instead of creating a separate issue for every container, I'm going to list all container styling issues below:
> Container width for Send/Receive/Transactions and Buy/Sell is different from Home

This was fixed on earlier version

> Content padding is messed up under Transactions

this was missed on last version

> Odd formatting:
> Please use a standard formatting for all headers and text across all screens: Send/Receive/Transactions are all different. Headers (labels) are ORANGE on Send, and the font is much smaller when compared to 'Receive', for instance.

this was fixed on earlier version


> Let's not re-invent the wheel. So if you could replicate the same styling of 'Send' screen to be the standard across all screen, it would be great.

this too.


> Under Buy/Sell, header text and AccountID are all messed up, center aligned (while everything on the app is not)

This was already discussed, and some fixes are applied, if you have more insights then open another issue where we can explore all the details

> FIX:
> 
> Please use a standard CSS class for all headers and text.

It was handled like that from the beginning as we already discussed, but there are sometimes typos, or other components sometimes get in the way, or other weird and unexpected behaviour.

**Comment by moatazkhalifa** [comment] 2020-08-31 12:51
Everything seems fine except for the last issue:

Under Buy/Sell, header text and AccountID are all messed up, center aligned (while everything on the app is not)

![Screenshot_20200831-144748_CR8 Wallet](https://user-images.githubusercontent.com/60157931/91721438-097e0980-eb99-11ea-9b0a-93fad6c81944.jpg)

Please keep the "You need to verify..." text on one line, and the account ID on one line as well. Please use the same styling as on Receive tab as the font seems bigger for the account ID

Also please change the button colors so the top button is in Orange and the second one is in light color

**Comment by t3nshi** [comment] 2020-08-31 14:01
Thank you, since this is explicit, this is really clear and straight forward.. the issue is as I mentioned, that this is not part of the app itself... it is an external complement, so we need to use a way to pass the styles in cumbersome ways... so it is not going to be ready for next version. I will let you know about it.

**Closed as completed** 2020-09-11 13:22 UTC
Labels: UI, on hold
