### ISSUE TITLE
[UI-FIX] Text is partially behind the iPhone XS notch

### ISSUE THREAD

**Issue by Marec4** [asgiom/cr8-brm-mobile-issues#56] opened 2020-09-04 05:52 UTC
**Section or interface element**
CR8 Wallet setup

**Reason**
Text is partially hidden behind the iPhone XS notch. Although the screenshot doesn't show the notch (I painted one on the picture) you can clearly see that the text is way too close to the top.

**Description**
Text should be fully visible.

**Screenshots**
![2020-09-03](https://user-images.githubusercontent.com/25827470/92204314-dd5dd380-ee8b-11ea-96b1-834af114d231.png)

**Comment by t3nshi** [comment] 2020-09-04 13:44
yes, I confirmed this. I will see how we can solve it as soon as possible, let you know about it soon. Thanks for reporting

**Comment by t3nshi** [comment] 2020-09-10 13:45
We need to sort out some minor stuff but this is solved. please confirm to close the issue.

**Comment by t3nshi** [comment] 2020-09-11 16:51
@Marec4 did you had a chance to check?

**Comment by t3nshi** [comment] 2020-09-11 17:31
Since is the only issue left for this milestone I will close it since we could verified fixed on simulators and one actual iphone... so If this issue is still there for your phone.. please reopen or let us know.

**Closed as completed by t3nshi** 2020-09-11 17:31 UTC
Labels: UI, test
