### ISSUE TITLE
[UI-FIX] visit button goes white

### ISSUE THREAD

**Issue by neilbirtles** [asgiom/cr8-brm-mobile-issues#66] opened 2020-09-06 05:21 UTC
After clicking the "visit" button for a casino and then coming back to the cr8 wallet with the phones back button the visit button is just plain white - button still works though. 

Phone is Google pixel 3a, android 10 patched to 5th aug security updates

![Screenshot_20200906-061549](https://user-images.githubusercontent.com/10454207/92318781-0fe10b00-f009-11ea-84f3-4c95ae23fc92.png)

**Comment by t3nshi** [comment] 2020-09-07 14:02
When reporting an issue please check if it was already reported, if it was and is closed but you have the same issue reopen it or ask for it to be reopened, otherwise add a new issue. This issue is already known and reported, this will be closed as a duplicate of #48 . Please keep track of this on the already reported issue. Thanks

**Closed as completed by t3nshi** 2020-09-07 14:02 UTC
Labels: duplicate, UI
