### ISSUE TITLE
[BUG] App asks for Fingerprint instead of PIN when connecting to OPIBIS, notification says CasinoCoin wallet

### ISSUE THREAD

**Issue by moatazkhalifa** [asgiom/cr8-brm-mobile-issues#28] opened 2020-08-19 18:53 UTC
As the title says, below is a screenshot

![Screenshot_20200819-205042_CR8 Wallet](https://user-images.githubusercontent.com/60157931/90677631-eaf54580-e25d-11ea-83f1-0ff31d069f71.jpg)

Device: Samsung S9+
Android 10

**Comment by t3nshi** [comment] 2020-08-19 20:26
We will fix the message, but if biometrics are enabled then this is the expected behaviour. In settings you can disable the biometrics to be asked again with your PIN

**Comment by moatazkhalifa** [comment] 2020-08-19 20:55
It was asking for PIN, then suddenly it switched to Fingerprint. 

If, during the setup, we ask for PIN, then default should always be PIN.

If default is going to be Fingerprint, then we ask for Fingerprint during setup.

Or we make the user choose whatever they prefer. Simple.

**Comment by t3nshi** [comment] 2020-08-19 20:57
it is like that, You might have enabled fingerprint on the settings screen. And it is weird since it is not something that can be enabled by accident since you need to input your PIN to enable it.

**Comment by t3nshi** [comment] 2020-08-19 20:58
If you go to settings you can disable it again. I will ask for your fingerprint to confirm

**Comment by moatazkhalifa** [comment] 2020-08-19 21:00
I have disabled it now. No idea how it got enabled really.

Could you change CasinoCoin wallet to CR8 Wallet please

**Comment by t3nshi** [comment] 2020-08-19 21:03
Yes sure!

**Comment by t3nshi** [comment] 2020-08-27 22:14
fixed on 0.4.7

**Closed as completed by t3nshi** 2020-08-27 22:14 UTC
Labels: bug
