### ISSUE TITLE
KYC Capture image #2

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#10] opened 2020-08-18 14:40 UTC
connected with issue 8.

KYC section. Huawei p20 pro - no capture image function. When i click on capture image it only allows me option to upload an image file and not open the camera. It automatically opens to my image galleryand no option to use built in camera to take a photo for selfie etc.

**Comment by danielwwf** [comment] 2020-08-18 14:50
Duplicate of https://github.com/asgiom/cr8-brm-mobile-issues/issues/8

**Closed as completed by danielwwf** 2020-08-18 14:50 UTC
Labels: duplicate
