### ISSUE TITLE
Delete Contacts

### ISSUE THREAD

**Issue by Mattch33** [asgiom/cr8-brm-mobile-issues#58] opened 2020-09-04 13:37 UTC
Once a contact has been added to the 'adress book' its not possible to delete that contact. 

Please add delete option.

**Comment by t3nshi** [comment] 2020-09-04 13:45
This is not a bug. That functionality does not exist yet, but it is a nice addition. I will look into adding it through adding a edit contact page.

**Comment by danielwwf** [comment] 2020-09-04 13:48
The app needs a propper address book, it's a mandatory feature all modern wallets have these days.

**Comment by t3nshi** [comment] 2020-09-04 13:58
So we all agree.. nice!

**Comment by danielwwf** [comment] 2020-09-04 14:02
Please make sure that the address book can be accessed through the settings as its own menu item. Thanks

**Comment by t3nshi** [comment] 2020-09-04 14:06
this is already being addressed in #59 . As I will do all I can to include it as soon as possible, it requires some work so don't expect me to finish within the next hour. Follow the mentioned issue to be in the loop... stay tuned.

**Comment by danielwwf** [comment] 2020-09-04 14:12
sounds solid :)

**Comment by danielwwf** [comment] 2020-09-06 12:07
deleting works

**Closed as completed by danielwwf** 2020-09-06 12:07 UTC
Labels: enhancement, test
