### ISSUE TITLE
iOS Dark Mode - Can't see DOB when setting up wallet. White on White [UI-FIX]

### ISSUE THREAD

**Issue by NKHund** [asgiom/cr8-brm-mobile-issues#61] opened 2020-09-04 18:00 UTC
**Section or interface element**
Explain what screen, or interface elements needs adjustment

**Reason**
Explain why this adjustment improves the look and feel 
or how it will align with branding guidelines

**Description**
A clear and concise description of how the look and feel should be.

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment] 2020-09-04 20:50
I appreciate you took the effort to report this... but next time save time using the search bar to see if your issue was already reported. We will close this as this is a duplicate of #53 . to be in the loop please keep track of that issue instead. And for future ref, you are required to fill the template so we can understand and reproudce reliably an issue. keep in mind that UI fix is for uncomfortable or ugly things... not for disruptive behavior, unaccessible items of breaking functionality.. that is a bug. Thanks for trying to help us improve.

**Closed as completed** 2020-09-04 20:50 UTC
Labels: duplicate, UI
