### ISSUE TITLE
Share QR code

### ISSUE THREAD

**Issue by Mattch33** [asgiom/cr8-brm-mobile-issues#60] opened 2020-09-04 13:41 UTC
We need an option to send a QR code with data (amount/dest tag/ memo) to multiple people.

**Comment by t3nshi** [comment] 2020-09-04 13:47
That sounds right. I will look into what we need to share the qrcode image through the way we already use to share the text.

**Comment by t3nshi** [comment] 2020-09-18 18:01
this needs more work... the implementation is sharing a QR that does not include full information as it should be

**Comment by t-jacobi** [comment] 2020-09-29 17:12
QR Code will be shared on 0.5.8 but isn't usable see #116

**Comment by danielwwf** [comment] 2020-09-29 23:29
Sharing doesnt work apps like whatsapp, because it is not listed

![image](https://user-images.githubusercontent.com/30388756/94626916-69f98700-02bc-11eb-90ef-ea5d03c67e11.png)

**Comment by t3nshi** [comment] 2020-09-30 17:55
> QR Code will be shared on 0.5.8 but isn't usable see #116

I don't understand why you say it is not usable. I don't get your point.

**Comment by t3nshi** [comment] 2020-09-30 17:58
> Sharing doesnt work apps like whatsapp, because it is not listed
> 
Can you open an Issue with all details and steps to reproduce? on the 4 devices at hand It can be shared on 2 of them to whatsapp... and that's only because the other 2 don't have any whatsapp. 
I might be wrong, but I think the functionality as requested in this  feature request is there... If you do agree, then the additional bugs can be dealt on a new thread.

**Comment by t3nshi** [comment] 2020-10-05 14:01
Well as we already said, there is a known issue with the sharing of QR code image that is being addressed, but that clearly shows that the QR itself works, so this issue is no longer relevant. I will be closing this for now. If the other issue mentioned can be reproduced,  and can be provided with related information please post a new issue se we take care of it. Thanks.

**Closed as completed by t3nshi** 2020-10-05 14:01 UTC
Labels: enhancement
