### ISSUE TITLE
[UI-FIX]

### ISSUE THREAD

**Issue by Mattch33** [asgiom/cr8-brm-mobile-issues#45] opened 2020-08-29 18:30 UTC
QR code on Samsung S9 isn't aligned correctly. Cannot read QR code.

**Comment by Mattch33** [comment] 2020-08-29 18:35
![Screenshot_20200829-193354_CR8 Wallet](https://user-images.githubusercontent.com/65967421/91643858-cbfd6d00-ea2e-11ea-9aeb-935ad64482b9.jpg)

**Comment by danielwwf** [comment] 2020-08-31 12:44
Duplicate of https://github.com/asgiom/cr8-brm-mobile-issues/issues/44

**Closed as completed by danielwwf** 2020-08-31 12:44 UTC
Labels: UI
