### ISSUE TITLE
[BUG] Auto logout doesn't seem to work

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#83] opened 2020-09-10 11:34 UTC
**Describe the bug**
Set the auto logout feature to 1 in Settings
Leave the device unlocked for >1 minute
(App can be in the foreground or background

**To Reproduce**
1. Go to Settings
2. Set 'Timeout to auto-logout' to 1
3. Leave the device without touching it (app can be in the fore or background while waiting)
4. Resume using the app

**Expected behavior**
User should be logged out and have to enter pin in order to resume using the app

**Smartphone (please complete the following information):**
 - Device: Samsung S6
 - OS: Android
 - OS Version 7.0
 - App Version 0.5.2

**Comment by danielwwf** [comment] 2020-09-10 11:51
duplicate of https://github.com/asgiom/cr8-brm-mobile-issues/issues/70

**Closed as completed by danielwwf** 2020-09-10 11:51 UTC
Labels: bug
